### ISSUE TITLE
Long annotations not showing up on listen page

### ISSUE THREAD

**Issue by JessCappadonna** [QutBioacoustics/baw-server#337] opened 2017-07-20 01:14 UTC
Today working with Ivan, we discovered we can't see a 30-second annotation intended to indicate that a plane was going throughout the entire segment [HERE](https://www.ecosounds.org/listen/262849?start=1380&end=1410), and it apparently was accidently tagged as "Eastern Bristlebird" rather than "Plane", but there is no way for me to correct this tag since I can't see the annotation. I suspect we can't see it because the boundaries are alongside the right and left segment borders, as this was a bug in the past, though I thought it had been fixed. You can see the annotation [HERE](https://www.ecosounds.org/library/262849/audio_events/190981) realizing that a few seconds up buffer have been added. 

Yvonne told us she has experiences this often but didn't report it since she found a work around, but the work around couldn't be duplicated in this case so perhaps discuss this with her to understand the larger issue.

**Comment by atruskie** [comment] 2017-07-21 01:36
Closing as duplicate of https://github.com/QutBioacoustics/baw-client/issues/268 and https://github.com/QutBioacoustics/baw-client/issues/276

**Closed by atruskie** 2017-07-21 01:36 UTC
Labels: bug, duplicate, feature: annotating/tagging, triage:medium
