### ISSUE TITLE
"Unknown" user making annotations and tags in private project 

### ISSUE THREAD

**Issue by JessCappadonna** [QutBioacoustics/baw-server#260] opened 2016-02-29 03:11 UTC
My understanding this that my project should be private, and thus people can't see, annotate, or tag project data through the listen page. However, this morning I noticed under 'Recent Annotations' there were several annotations listed as ""(not tagged)" by (unknown)". I understand people can create annotations without tagging, but it baffles me how the annotator can be unknown, and this seems to be an issue with the system's privacy settings. 

For screenshot, see https://gyazo.com/91e37606f47a7b93e82baca057b5636f

**Comment by atruskie** [comment] 2016-02-29 03:47
I went to every site in that project as normal user and Admin.

Could not reproduce. Did you change the data?
Checked multiple different sites.

Closing for now. *Reopen* this issue is you notice the issue again.

- please provide exact URL
- another screenshot if it happens again.

**Closed by atruskie** 2016-02-29 03:47 UTC
Labels: can't reproduce

**Comment by atruskie** [comment] 2016-02-29 03:52
https://github.com/QutBioacoustics/baw-server/blob/develop/app/views/sites/show.html.haml#L84

That's the line that could cause the problem. I've checked the database though and no annotation has both creator and updater set to null.
